updating to bash script due to error

diff --git a/AzureDevOps/pipeline.yaml b/AzureDevOps/pipeline.yaml
--- a/AzureDevOps/pipeline.yaml
+++ b/AzureDevOps/pipeline.yaml
@@ -65,10 +65,16 @@ stages:
     - task: DockerInstaller@0
   
     - script: |
-        docker network rm shared-test-network || true
+        echo Stopping containers using the network (if any)...
+        docker ps -q --filter "network=shared-test-network" | for /F %i in ('more') do docker stop %i && docker rm %i
+
+        echo Attempting to remove shared-test-network...
+        docker network rm shared-test-network || echo "Network removal failed (may not exist or in use). Continuing..."
+
+        echo Creating shared-test-network...
         docker network create shared-test-network
-      shell: bash
       displayName: 'Ensure Shared Network is Clean'
+
 
 
     # Start the mock server (WireMock)
